### PR TITLE
Add i18n 'ed' comparision on scenario_outline keyword

### PR DESCRIPTION
**Pull request by clicman**
Hi! During testing I found problem with SCENARIO_OUTLINE_KEYWORD comparsion in non-English language case. This PR fixes it.

### CODE REVIEW

**Comment by gvvinblade** [comment]
We'll try to release it in a couple of days (last release has been quite a long time ago, so, we need to restore and setup keys for maven deployment). Thanks for the fix)

**Comment by gvvinblade** [comment]
Deployed, is waiting for synchronization with the maven central repo

**Comment by clicman** [comment]
Ok. Thanks.

**Comment by kirlionik** [comment]
I have released it into nexus repository. Now we are waiting synchronization with central maven repository.

**Comment by kirlionik** [comment]
Now in central maven repo http://search.maven.org/#artifactdetails%7Ccom.github.kirlionik%7Callure-cucumber-plugin%7C1.0.2%7Cjar

**Pull request merged**
